name: Publish Docker image

on:
  push:
    branches:
      - master
jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io/arugal-docker/apisix
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        run: |
          docker build -t ghcr.io/arugal-docker/apisix/apisix:${{ github.sha }} -f docker/Dockerfile .
          docker push ghcr.io/arugal-docker/apisix/apisix:${{ github.sha }}
