name: Release

on:
  push:
    tags:
      - 'v*'
jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io/arugal-docker/apisix
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        run: |
          docker build -t ghcr.io/arugal-docker/apisix/apisix:${{ steps.get_version.outputs.VERSION }} -f docker/Dockerfile .
          docker push ghcr.io/arugal-docker/apisix/apisix:${{ steps.get_version.outputs.VERSION }}
          
          
